#!/usr/bin/env bash

# cat .files | xargs -I % bash -c 'realpath %' | xargs -I % find % -mindepth 1 -maxdepth 1 -type d | fzf

hydrate() {
    if [ -f $2/.txs ]; then
        tmux send-keys -t $1 "source $2/.tmux-sessioniser" c-M
    elif [ -f $HOME/.tmux-sessioniser ]; then
        tmux send-keys -t $1 "source $HOME/.tmux-sessioniser" c-M
    fi
}

switch_to() {
    if [[ -z $TMUX ]]; then 
        tmux attach-session -t $1
    else
        tmux switch-client -t $1
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}

if [[ $# -eq 1 ]]; then 
    selected=$1
else
    selected=$(cat ~/.workspace_dirs | xargs -I % bash -c 'realpath %' | xargs -I % find % -mindepth 1 -maxdepth 2 -type d | fzf) 
fi

if [[ -z $selected ]]; then
    exit 1
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    hydrate $selected_name $selected
#    exit 0
fi

if ! has_session $selected_name; then
    tmux new-session -ds $selected_name -c $selected
    hydrate $selected_name $selected
fi
switch_to $selected_name

